server:
  port: 8080

spring:
  application:
    name: @project.name@
    description: @project.description@

service:
  backend:
    exchange:
      read-timeout: 10000
      write-timeout: 10000
      connect-timeout: 1000


management:
  health:
    circuitbreakers:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator

